---
title: "Gastos Bradesco"
output: flexdashboard::flex_dashboard
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(dplyr)
library(ggplot2)
source("extracao_compras.r")
```

Column {.sidebar data-width=520}
-----------------------------------------------------------------------

```{r}
textInput('username', 'User', placeholder = 'Usuário')
passwordInput('password', 'Password', placeholder = '***')
actionButton("loga", "Login")

#observeEvent(input$loga,{
#  print("rodando")

  #base = extrai.compras()

  base = readRDS("exemplo_gastos.rds")
  
  dataset <- reactive({base})
  
  dateRangeInput("dates", 
                 label = h3("Datas para análise"),
                 min = min(base$data.compra),
                 max = max(base$data.compra),
                 start = min(base$data.compra),
                 end = max(base$data.compra))
  
  x<-reactive({input$dates[2]})
  
  renderTable({

    if(is.na(x())){
      dataset() %>% 
        filter(data.compra >= input$dates[1]) %>% 
        mutate(data.compra = as.character(format(data.compra,"%d/%m/%y %H:%m"))) %>% 
        `colnames<-`(c("Final","Data","Valor","Estabelecimento","Tag")) %>% 
        select(-"Final")
      
    }else{
        dataset() %>% 
          filter(data.compra >= input$dates[1], 
                 data.compra <= input$dates[2]) %>% 
          mutate(data.compra = as.character(format(data.compra,"%d/%m/%y %H:%m"))) %>% 
          `colnames<-`(c("Final","Data","Valor","Estabelecimento","Tag")) %>% 
          select(-"Final")
  }
  })
#})
```

Column
-----------------------------------------------------------------------

## Teste gráfico

```{r}
renderPlot({
    if(is.na(x())){
        dataset() %>% 
        filter(data.compra >= input$dates[1])%>% ggplot(aes(x=valor)) + geom_histogram()
      
    }else{
        dataset() %>% 
          filter(data.compra >= input$dates[1], 
                 data.compra <= input$dates[2]) %>% ggplot(aes(x=valor)) + geom_histogram()
    }
  
})
```

